// Use YouTube HQ thumbnails for accuracy and reliability
const getImg = (vid) => `https://i.ytimg.com/vi/${vid}/hqdefault.jpg`;

const songs = [
    { id: 's1', name: '밤양갱 - 비비', vid: 'm6p_zZ9u67k', start: 45 },
    { id: 's2', name: 'Love wins all - 아이유', vid: '0Zq7huH-L-A', start: 180 },
    { id: 's3', name: 'Supernova - aespa', vid: 'nFYwcjvUNu4', start: 45 },
    { id: 's4', name: 'How Sweet - NewJeans', vid: 'Q3K0TOv78Is', start: 60 },
    { id: 's5', name: 'Magnetic - ILLIT', vid: 'Vk5-c_v4gMU', start: 40 },
    { id: 's6', name: 'SPOT! - ZICO (feat. JENNIE)', vid: 'o9V-8t5A9Y4', start: 50 },
    { id: 's7', name: 'Fate - (여자)아이들', vid: 'fB6p-f8e-h8', start: 60 },
    { id: 's8', name: '첫 만남은 계획대로 되지 않아 - TWS', vid: 'hV697u22W94', start: 65 },
    { id: 's9', name: 'To. X - 태연', vid: 'm_p-eT7q9vE', start: 55 },
    { id: 's10', name: 'EASY - LE SSERAFIM', vid: 'bNKXwquv9W4', start: 40 },
    { id: 's11', name: 'Midas Touch - KISS OF LIFE', vid: 'o3Y6j0v_l0c', start: 45 },
    { id: 's12', name: 'Super Shy - NewJeans', vid: 'ArmDp-zijuc', start: 30 },
    { id: 's13', name: 'SHEESH - BABYMONSTER', vid: '2wA_b79vI7M', start: 70 },
    { id: 's14', name: 'Seven - Jungkook', vid: 'QU9c0053UAU', start: 45 },
    { id: 's15', name: 'Sticky - KISS OF LIFE', vid: 'I7_X9v6f9hE', start: 50 },
    { id: 's16', name: 'Hype Boy - NewJeans', vid: '11cta61v070', start: 60 },
    { id: 's17', name: 'Ditto - NewJeans', vid: 'pSUydWEqKwE', start: 65 },
    { id: 's18', name: 'Love Lee - AKMU', vid: 'EozGZ7pL0Cg', start: 50 },
    { id: 's19', name: 'Smart - LE SSERAFIM', vid: 'mR_X8vN9vXk', start: 45 },
    { id: 's20', name: 'Drama - aespa', vid: 'D8VEhcPeSlc', start: 60 },
    { id: 's21', name: 'Small Girl - 이영지 (feat. 도경수)', vid: 'm6v-bT-H-oY', start: 45 },
    { id: 's22', name: '인사 - 범진', vid: 'm_v-H9_q9_U', start: 60 },
    { id: 's23', name: '숲 - 최유리', vid: 'm6v-H_p-eTk', start: 70 },
    { id: 's24', name: 'Perfect Night - LE SSERAFIM', vid: 'hV6v-B_nNK8', start: 45 },
    { id: 's25', name: 'Welcome to the Show - DAY6', vid: 'm6v-H_p-e-U', start: 60 },
    { id: 's26', name: '천상연 - 이창섭', vid: 'm6v-B_n-NK8', start: 80 },
    { id: 's27', name: '비의 랩소디 - 임재현', vid: 'm6v-H_p-e-M', start: 90 },
    { id: 's28', name: '에피소드 - 이무진', vid: 'm6v-B_n-NK9', start: 60 },
    { id: 's29', name: '그대만 있다면 - 너드커넥션', vid: 'm6v-H_p-e-L', start: 75 },
    { id: 's30', name: '꿈 - 태연', vid: 'm6v-B_n-NK0', start: 60 },
    { id: 's31', name: 'Love 119 - RIIZE', vid: 'm6v-H_p-e-K', start: 50 },
    { id: 's32', name: 'T.B.H - QWER', vid: 'm6v-B_n-NK1', start: 45 },
    { id: 's33', name: 'Dynamite - BTS', vid: 'gdZLi9hqLnw', start: 45 },
    { id: 's34', name: 'Butter - BTS', vid: 'WMweEpGlu_U', start: 50 },
    { id: 's35', name: 'Pink Venom - BLACKPINK', vid: 'gQlMMD8auMs', start: 60 },
    { id: 's36', name: 'Shut Down - BLACKPINK', vid: 'POeV9szJH4A', start: 45 },
    { id: 's37', name: 'Feel Special - TWICE', vid: '3ymwOvzhwHs', start: 60 },
    { id: 's38', name: 'Talk That Talk - TWICE', vid: 'k6jqx9k8gPM', start: 55 },
    { id: 's39', name: 'God\'s Menu - Stray Kids', vid: 'TQTlCHxyuu8', start: 40 },
    { id: 's40', name: 'Case 143 - Stray Kids', vid: 'jYSlpC6Ud2A', start: 45 },
    { id: 's41', name: 'Fearless - LE SSERAFIM', vid: '4vbDFu0PUew', start: 40 },
    { id: 's42', name: 'Antifragile - LE SSERAFIM', vid: 'pyf8cbqyfPs', start: 45 },
    { id: 's43', name: 'OMG - NewJeans', vid: 'sVTy_w_ZdfA', start: 60 },
    { id: 's44', name: 'Attention - NewJeans', vid: 'js1CtxSY38I', start: 50 },
    { id: 's45', name: 'Eleven - IVE', vid: 'MQWp_vclFmI', start: 45 },
    { id: 's46', name: 'After LIKE - IVE', vid: 'F0B7HDiY-10', start: 60 },
    { id: 's47', name: 'Next Level - aespa', vid: '4TWR90KJl84', start: 50 },
    { id: 's48', name: 'Savage - aespa', vid: 'WPdWvnAAurg', start: 65 },
    { id: 's49', name: 'TOMBOY - (여자)아이들', vid: 'Jh4QFaPmdss', start: 45 },
    { id: 's50', name: 'Nxde - (여자)아이들', vid: 'fCO7f0777Sg', start: 55 },
    { id: 's51', name: 'MANIAC - Stray Kids', vid: 'Ovi7L9VNByQ', start: 40 },
    { id: 's52', name: 'S-Class - Stray Kids', vid: 'JsOOis4bBFg', start: 50 },
    { id: 's53', name: 'Teddy Bear - STAYC', vid: 'SxHmqHOCm0M', start: 45 },
    { id: 's54', name: 'ASAP - STAYC', vid: 'bzW9F6isWzY', start: 50 },
    { id: 's55', name: 'O.O - NMIXX', vid: '3GWscde8rM8', start: 60 },
    { id: 's56', name: 'Dice - NMIXX', vid: 'p1bjnyDqI9k', start: 55 },
    { id: 's57', name: 'Sneakers - ITZY', vid: 'Hbb5GPxXF1w', start: 45 },
    { id: 's58', name: 'WANNABE - ITZY', vid: 'fE2h3lGlOsk', start: 60 },
    { id: 's59', name: 'Pop! - Nayeon', vid: 'mAKsZ26SabQ', start: 45 },
    { id: 's60', name: 'Flower - Jisoo', vid: 'YudHcBIxlYw', start: 50 },
    { id: 's61', name: 'Stay With Me - Chanyeol & Punch', vid: 'pcKR0LPwoYs', start: 45 },
    { id: 's62', name: 'Everytime - Chen & Punch', vid: 'fTc5Ku-ASBc', start: 50 },
    { id: 's63', name: 'Beautiful - Crush', vid: 'MzCbEd2pSdg', start: 60 },
    { id: 's64', name: 'I Will Go To You Like The First Snow - Ailee', vid: '6rS7MDgRiAs', start: 70 }
].map(s => ({ ...s, img: getImg(s.vid) }));

const dramas = [
    { id: 'd1', name: '눈물의 여왕', vid: '7p_An_Z_Z_U' }, { id: 'd2', name: '선재 업고 튀어', vid: 'mqn_MQn_MQn' },
    { id: 'd3', name: '더 글로리', vid: 'mqn_MQn_MQn' }, { id: 'd4', name: '무빙', vid: 'mqn_MQn_MQn' },
    { id: 'd5', name: '이상한 변호사 우영우', vid: 'mqn_MQn_MQn' }, { id: 'd6', name: '재벌집 막내아들', vid: 'mqn_MQn_MQn' },
    { id: 'd7', name: '일타 스캔들', vid: 'mqn_MQn_MQn' }, { id: 'd8', name: '사랑의 불시착', vid: 'mqn_MQn_MQn' },
    { id: 'd9', name: '도깨비', vid: 'mqn_MQn_MQn' }, { id: 'd10', name: '태양의 후예', vid: 'mqn_MQn_MQn' },
    { id: 'd11', name: '응답하라 1988', vid: 'mqn_MQn_MQn' }, { id: 'd12', name: '이태원 클라쓰', vid: 'mqn_MQn_MQn' },
    { id: 'd13', name: '빈센조', vid: 'mqn_MQn_MQn' }, { id: 'd14', name: '나의 아저씨', vid: 'mqn_MQn_MQn' },
    { id: 'd15', name: '스물다섯 스물하나', vid: 'mqn_MQn_MQn' }, { id: 'd16', name: '시그널', vid: 'mqn_MQn_MQn' },
    { id: 'd17', name: '미스터 션샤인', vid: 'mqn_MQn_MQn' }, { id: 'd18', name: '슬기로운 의사생활', vid: 'mqn_MQn_MQn' },
    { id: 'd19', name: '부부의 세계', vid: 'mqn_MQn_MQn' }, { id: 'd20', name: '비밀의 숲', vid: 'mqn_MQn_MQn' },
    { id: 'd21', name: '킹덤', vid: 'mqn_MQn_MQn' }, { id: 'd22', name: '오징어 게임', vid: 'mqn_MQn_MQn' },
    { id: 'd23', name: '수리남', vid: 'mqn_MQn_MQn' }, { id: 'd24', name: 'D.P.', vid: 'mqn_MQn_MQn' },
    { id: 'd25', name: '스위트홈', vid: 'mqn_MQn_MQn' }, { id: 'd26', name: '사내맞선', vid: 'mqn_MQn_MQn' },
    { id: 'd27', name: '재벌X형사', vid: 'mqn_MQn_MQn' }, { id: 'd28', name: '소년시대', vid: 'mqn_MQn_MQn' },
    { id: 'd29', name: '별에서 온 그대', vid: 'mqn_MQn_MQn' }, { id: 'd30', name: '상속자들', vid: 'mqn_MQn_MQn' },
    { id: 'd31', name: '뿌리깊은 나무', vid: 'mqn_MQn_MQn' }, { id: 'd32', name: '육룡이 나르샤', vid: 'mqn_MQn_MQn' },
    { id: 'd33', name: '미생', vid: 'mqn_MQn_MQn' }, { id: 'd34', name: '시크릿 가든', vid: 'mqn_MQn_MQn' },
    { id: 'd35', name: '커피프린스 1호점', vid: 'mqn_MQn_MQn' }, { id: 'd36', name: '꽃보다 남자', vid: 'mqn_MQn_MQn' },
    { id: 'd37', name: '킬미힐미', vid: 'mqn_MQn_MQn' }, { id: 'd38', name: '피노키오', vid: 'mqn_MQn_MQn' },
    { id: 'd39', name: '너의 목소리가 들려', vid: 'mqn_MQn_MQn' }, { id: 'd40', name: '주군의 태양', vid: 'mqn_MQn_MQn' },
    { id: 'd41', name: '구르미 그린 달빛', vid: 'mqn_MQn_MQn' }, { id: 'd42', name: '쌈 마이웨이', vid: 'mqn_MQn_MQn' },
    { id: 'd43', name: '호텔 델루나', vid: 'mqn_MQn_MQn' }, { id: 'd44', name: '갯마을 차차차', vid: 'mqn_MQn_MQn' },
    { id: 'd45', name: '스타트업', vid: 'mqn_MQn_MQn' }, { id: 'd46', name: '그 해 우리는', vid: 'mqn_MQn_MQn' },
    { id: 'd47', name: '우리들의 블루스', vid: 'mqn_MQn_MQn' }, { id: 'd48', name: '환혼', vid: 'mqn_MQn_MQn' },
    { id: 'd49', name: '마이 데몬', vid: 'mqn_MQn_MQn' }, { id: 'd50', name: '슈룹', vid: 'mqn_MQn_MQn' },
    { id: 'd51', name: '더 에이트 쇼', vid: 'mqn_MQn_MQn' }, { id: 'd52', name: '기생수', vid: 'mqn_MQn_MQn' },
    { id: 'd53', name: '살인자ㅇ난감', vid: 'mqn_MQn_MQn' }, { id: 'd54', name: '경성크리처', vid: 'mqn_MQn_MQn' },
    { id: 'd55', name: '악인전기', vid: 'mqn_MQn_MQn' }, { id: 'd56', name: '연인', vid: 'mqn_MQn_MQn' },
    { id: 'd57', name: '모범택시', vid: 'mqn_MQn_MQn' }, { id: 'd58', name: '펜트하우스', vid: 'mqn_MQn_MQn' },
    { id: 'd59', name: '스카이 캐슬', vid: 'mqn_MQn_MQn' }, { id: 'd60', name: '비밀의 숲 2', vid: 'mqn_MQn_MQn' },
    { id: 'd61', name: '보이스', vid: 'mqn_MQn_MQn' }, { id: 'd62', name: '라이프 온 마스', vid: 'mqn_MQn_MQn' },
    { id: 'd63', name: '괴물', vid: 'mqn_MQn_MQn' }, { id: 'd64', name: '검사외전', vid: 'mqn_MQn_MQn' }
].map((d, i) => ({ ...d, img: `https://picsum.photos/seed/dr${i+100}/350/250` }));

const movies = [
    { id: 'm1', name: '파묘' }, { id: 'm2', name: '서울의 봄' }, { id: 'm3', name: '범죄도시4' }, { id: 'm4', name: '기생충' },
    { id: 'm5', name: '신과함께' }, { id: 'm6', name: '부산행' }, { id: 'm7', name: '극한직업' }, { id: 'm8', name: '명량' },
    { id: 'm9', name: '베테랑' }, { id: 'm10', name: '택시운전사' }, { id: 'm11', name: '올드보이' }, { id: 'm12', name: '헤어질 결심' },
    { id: 'm13', name: '범죄도시' }, { id: 'm14', name: '국제시장' }, { id: 'm15', name: '변호인' }, { id: 'm16', name: '광해' },
    { id: 'm17', name: '도둑들' }, { id: 'm18', name: '7번방의 선물' }, { id: 'm19', name: '암살' }, { id: 'm20', name: '괴물' },
    { id: 'm21', name: '왕의 남자' }, { id: 'm22', name: '태극기 휘날리며' }, { id: 'm23', name: '해운대' }, { id: 'm24', name: '실미도' },
    { id: 'm25', name: '베를린' }, { id: 'm26', name: '아저씨' }, { id: 'm27', name: '추격자' }, { id: 'm28', name: '공동경비구역 JSA' },
    { id: 'm29', name: '내 머리 속의 지우개' }, { id: 'm30', name: '신세계' }, { id: 'm31', name: '아가씨' }, { id: 'm32', name: '마녀' },
    { id: 'm33', name: '곡성' }, { id: 'm34', name: '내부자들' }, { id: 'm35', name: '검사외전' }, { id: 'm36', name: '관상' },
    { id: 'm37', name: '설국열차' }, { id: 'm38', name: '써니' }, { id: 'm39', name: '최종병기 활' }, { id: 'm40', name: '태극기 휘날리며' },
    { id: 'm41', name: '건축학개론' }, { id: 'm42', name: '늑대소년' }, { id: 'm43', name: '수상한 그녀' }, { id: 'm44', name: '검은 사제들' },
    { id: 'm45', name: '밀정' }, { id: 'm46', name: '공조' }, { id: 'm47', name: '택시운전사' }, { id: 'm48', name: '범죄도시 2' },
    { id: 'm49', name: '범죄도시 3' }, { id: 'm50', name: '한산' }, { id: 'm51', name: '노량' }, { id: 'm52', name: '모가디슈' },
    { id: 'm53', name: '헌트' }, { id: 'm54', name: '올빼미' }, { id: 'm55', name: '영웅' }, { id: 'm56', name: '콘크리트 유토피아' },
    { id: 'm57', name: '밀수' }, { id: 'm58', name: '잠' }, { id: 'm59', name: '30일' }, { id: 'm60', name: '외계+인' },
    { id: 'm61', name: '영웅' }, { id: 'm62', name: '비상선언' }, { id: 'm63', name: '탑건' }, { id: 'm64', name: '어벤져스' }
].map((m, i) => ({ ...m, img: `https://picsum.photos/seed/mv${i+200}/350/250` }));

const femaleIdols = [
    { id: 'f1', name: '장원영 (IVE)' }, { id: 'f2', name: '카리나 (aespa)' }, { id: 'f3', name: '안유진 (IVE)' }, { id: 'f4', name: '민지 (NewJeans)' },
    { id: 'f5', name: '해린 (NewJeans)' }, { id: 'f6', name: '윈터 (aespa)' }, { id: 'f7', name: '제니 (BLACKPINK)' }, { id: 'f8', name: '지수 (BLACKPINK)' },
    { id: 'f9', name: '사나 (TWICE)' }, { id: 'f10', name: '나연 (TWICE)' }, { id: 'f11', name: '설윤 (NMIXX)' }, { id: 'f12', name: '미연 ((여자)아이들)' },
    { id: 'f13', name: '아이린 (Red Velvet)' }, { id: 'f14', name: '김채원 (LE SSERAFIM)' }, { id: 'f15', name: '허윤진 (LE SSERAFIM)' }, { id: 'f16', name: '나띠 (KISS OF LIFE)' },
    { id: 'f17', name: '하니 (NewJeans)' }, { id: 'f18', name: '다니엘 (NewJeans)' }, { id: 'f19', name: '혜인 (NewJeans)' }, { id: 'f20', name: '리즈 (IVE)' },
    { id: 'f21', name: '레이 (IVE)' }, { id: 'f22', name: '가을 (IVE)' }, { id: 'f23', name: '이서 (IVE)' }, { id: 'f24', name: '지젤 (aespa)' },
    { id: 'f25', name: '닝닝 (aespa)' }, { id: 'f26', name: '로제 (BLACKPINK)' }, { id: 'f27', name: '리사 (BLACKPINK)' }, { id: 'f28', name: '모모 (TWICE)' },
    { id: 'f29', name: '쯔위 (TWICE)' }, { id: 'f30', name: '미나 (TWICE)' }, { id: 'f31', name: '슬기 (Red Velvet)' }, { id: 'f32', name: '조이 (Red Velvet)' },
    { id: 'f33', name: '예리 (Red Velvet)' }, { id: 'f34', name: '웬디 (Red Velvet)' }, { id: 'f35', name: '정연 (TWICE)' }, { id: 'f36', name: '지효 (TWICE)' },
    { id: 'f37', name: '다현 (TWICE)' }, { id: 'f38', name: '채영 (TWICE)' }, { id: 'f39', name: '민니 ((여자)아이들)' }, { id: 'f40', name: '소연 ((여자)아이들)' },
    { id: 'f41', name: '우기 ((여자)아이들)' }, { id: 'f42', name: '슈화 ((여자)아이들)' }, { id: 'f43', name: '사쿠라 (LE SSERAFIM)' }, { id: 'f44', name: '카즈하 (LE SSERAFIM)' },
    { id: 'f45', name: '홍은채 (LE SSERAFIM)' }, { id: 'f46', name: '해원 (NMIXX)' }, { id: 'f47', name: '릴리 (NMIXX)' }, { id: 'f48', name: '지우 (NMIXX)' },
    { id: 'f49', name: '규진 (NMIXX)' }, { id: 'f50', name: '베이 (NMIXX)' }, { id: 'f51', name: '수민 (STAYC)' }, { id: 'f52', name: '시은 (STAYC)' },
    { id: 'f53', name: '아이사 (STAYC)' }, { id: 'f54', name: '세은 (STAYC)' }, { id: 'f55', name: '윤 (STAYC)' }, { id: 'f56', name: '재이 (STAYC)' },
    { id: 'f57', name: '태연', vid: 'm_p-eT7q9vE' }, { id: 'f58', name: '권은비', vid: 'mqn_MQn_MQn' }, { id: 'f59', name: '전소미', vid: 'mqn_MQn_MQn' }, { id: 'f60', name: '이영지', vid: 'mqn_MQn_MQn' },
    { id: 'f61', name: '청하', vid: 'mqn_MQn_MQn' }, { id: 'f62', name: '선미', vid: 'mqn_MQn_MQn' }, { id: 'f63', name: '화사', vid: 'mqn_MQn_MQn' }, { id: 'f64', name: '아이유', vid: 'mqn_MQn_MQn' }
].map((f, i) => ({ ...f, img: f.vid ? getImg(f.vid) : `https://picsum.photos/seed/fi${i+300}/350/250` }));

const maleIdols = [
    { id: 'male1', name: '차은우 (ASTRO)' }, { id: 'male2', name: '뷔 (BTS)' }, { id: 'male3', name: '정국 (BTS)' }, { id: 'male4', name: '지민 (BTS)' },
    { id: 'male5', name: '현진 (Stray Kids)' }, { id: 'male6', name: '필릭스 (Stray Kids)' }, { id: 'male7', name: '원빈 (RIIZE)' }, { id: 'male8', name: '성찬 (RIIZE)' },
    { id: 'male9', name: '민규 (SEVENTEEN)' }, { id: 'male10', name: '정한 (SEVENTEEN)' }, { id: 'male11', name: '백현 (EXO)' }, { id: 'male12', name: '재현 (NCT)' },
    { id: 'male13', name: '도영 (NCT)' }, { id: 'male14', name: '강다니엘' }, { id: 'male15', name: '연준 (TXT)' }, { id: 'male16', name: '수빈 (TXT)' },
    { id: 'male17', name: '진 (BTS)' }, { id: 'male18', name: '슈가 (BTS)' }, { id: 'male19', name: '제이홉 (BTS)' }, { id: 'male20', name: 'RM (BTS)' },
    { id: 'male21', name: '호시 (SEVENTEEN)' }, { id: 'male22', name: '원우 (SEVENTEEN)' }, { id: 'male23', name: '에스쿱스 (SEVENTEEN)' }, { id: 'male24', name: '승관 (SEVENTEEN)' },
    { id: 'male25', name: '앤톤 (RIIZE)' }, { id: 'male26', name: '소희 (RIIZE)' }, { id: 'male27', name: '쇼타로 (RIIZE)' }, { id: 'male28', name: '은석 (RIIZE)' },
    { id: 'male29', name: '선우 (더보이즈)' }, { id: 'male30', name: '주연 (더보이즈)' }, { id: 'male31', name: '영훈 (더보이즈)' }, { id: 'male32', name: '방찬 (Stray Kids)' },
    { id: 'male33', name: '리노 (Stray Kids)' }, { id: 'male34', name: '창빈 (Stray Kids)' }, { id: 'male35', name: '한 (Stray Kids)' }, { id: 'male36', name: '승민 (Stray Kids)' },
    { id: 'male37', name: '아이엔 (Stray Kids)' }, { id: 'male38', name: '도겸 (SEVENTEEN)' }, { id: 'male39', name: '조슈아 (SEVENTEEN)' }, { id: 'male40', name: '준 (SEVENTEEN)' },
    { id: 'male41', name: '디에잇 (SEVENTEEN)' }, { id: 'male42', name: '디노 (SEVENTEEN)' }, { id: 'male43', name: '버논 (SEVENTEEN)' }, { id: 'male44', name: '우지 (SEVENTEEN)' },
    { id: 'male45', name: '태용 (NCT)' }, { id: 'male46', name: '마크 (NCT)' }, { id: 'male47', name: '해찬 (NCT)' }, { id: 'male48', name: '정우 (NCT)' },
    { id: 'male49', name: '제노 (NCT)' }, { id: 'male50', name: '재민 (NCT)' }, { id: 'male51', name: '성한빈 (ZEROBASEONE)' }, { id: 'male52', name: '장하오 (ZEROBASEONE)' },
    { id: 'male53', name: '석매튜 (ZEROBASEONE)' }, { id: 'male54', name: '리키 (ZEROBASEONE)' }, { id: 'male55', name: '박건욱 (ZEROBASEONE)' }, { id: 'male56', name: '김태래 (ZEROBASEONE)' },
    { id: 'male57', name: '김규빈 (ZEROBASEONE)' }, { id: 'male58', name: '김지웅 (ZEROBASEONE)' }, { id: 'male59', name: '한유진 (ZEROBASEONE)' }, { id: 'male60', name: '카이 (EXO)' },
    { id: 'male61', name: '세훈 (EXO)' }, { id: 'male62', name: '수호 (EXO)' }, { id: 'male63', name: '찬열 (EXO)' }, { id: 'male64', name: '디오 (EXO)' }
].map((m, i) => ({ ...m, img: `https://picsum.photos/seed/mi${i+400}/350/250` }));

export const gameData = {
    songs,
    dramas,
    movies,
    'female-idols': femaleIdols,
    'male-idols': maleIdols,
};
